[package]
name = "zion"
version = "1.0.0"
authors = []

[addresses]
zion = "_"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dev-addresses]
zion = "0x8d57826749cd1bb57d8cce0c917c05fd9cab6e94168512a2b39b90d6fe3bc383"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]